/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    KeySelector: typeof import('./src/components/KeySelector.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
